# Dockerfile for ELK stack
# Elasticsearch, Logstash, Kibana 5.6.3
# Modified to run with the Azure Storage Emulator on Windows 10

FROM sebp/elk:562
LABEL maintainer="Ralph Willgoss https://github.com/ralphwillgoss"
LABEL version="0.1-alpha"

# Logstash Azure plugin to read data from Azure WAD tables
RUN /opt/logstash/bin/logstash-plugin install logstash-input-azurewadtable

# Customised logstash Azure WAD file to be able to read data from the emulator
COPY ./logstash-input-azurewadtable/azurewadtable.rb /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.12/lib/logstash/inputs/

# Add our customised config for logstash to look at our tables
COPY ./logstash-input-azurewadtable/azurewadtable.conf /etc/logstash/conf.d/azurewadtable.conf